#!/bin/bash

echo "🌐 Google OAuth Setup Instructions"
echo "=================================="
echo ""
echo "📋 To complete Google OAuth setup, you need to:"
echo ""
echo "1. SUPABASE DASHBOARD SETUP:"
echo "   • Go to: https://supabase.com/dashboard"
echo "   • Select your project: fheaayyooebdsppcymce"
echo "   • Go to: Authentication → Providers"
echo "   • Enable Google provider"
echo "   • Add your Site URL: http://localhost:5173"
echo "   • Add your Redirect URL: https://fheaayyooebdsppcymce.supabase.co/auth/v1/callback"
echo ""
echo "2. GOOGLE CONSOLE SETUP:"
echo "   • Go to: https://console.cloud.google.com"
echo "   • Create/select your project"
echo "   • Go to: APIs & Credentials → OAuth 2.0 Client IDs"
echo "   • Add authorized redirect URI:"
echo "     https://fheaayyooebdsppcymce.supabase.co/auth/v1/callback"
echo ""
echo "3. TEST GOOGLE LOGIN:"
echo "   • Your app now has Google login button"
echo "   • Click 'Google' tab in admin login"
echo "   • Login with your Google account"
echo "   • If your Gmail is kusbot114@gmail.com, you'll get admin access"
echo ""
echo "✅ Your credentials are already configured:"
echo "   • Client ID: 336380348397-rursc0nbq28f7jufh2uth82pmfrmm4q3.apps.googleusercontent.com"
echo "   • Supabase URL: https://fheaayyooebdsppcymce.supabase.co"
echo ""
echo "🎯 After setup, you can login with either:"
echo "   • Email/Password (for admin emails in .env)"
echo "   • Google OAuth (any Google account)"
