[build]
  publish  = "dist"
  command  = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# ----- Security headers (aman) -----
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-hashes' https://*.supabase.co https://*.google.com https://*.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' data: https://*.supabase.co wss://*.supabase.co https://*.google.com https://*.googleapis.com https://fonts.gstatic.com https://api.telegram.org; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self';"

# ----- Cache headers for assets -----
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "https://fheaayyooebdsppcymce.supabase.co/storage/v1/object/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ----- Redirect ke HTTPS (boleh tetap) -----
[[redirects]]
  from = "http://*"
  to   = "https://:splat"
  status = 301

# ----- (Opsional) Map Functions dulu, kalau kamu punya /api/* -----
# Taruh rule ini SEBELUM fallback SPA
# [[redirects]]
#   from = "/api/*"
#   to   = "/.netlify/functions/:splat"
#   status = 200

# ----- INI YANG WAJIB: SPA fallback -----
# HARUS di paling bawah
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Template env (tidak berpengaruh ke build)
[template.environment]
  VITE_SUPABASE_URL       = "Your Supabase URL"
  VITE_SUPABASE_ANON_KEY  = "Your Supabase Anon Key"
  VITE_SITE_NAME          = "Kopi Pendekar"
  VITE_ADMIN_EMAILS       = "Your admin email"
  VITE_PAYMENT_INFO_TEXT  = "Your payment instructions"
  VITE_QRIS_IMAGE_URL     = "Your QRIS image URL"
