[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co https://*.google.com https://*.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.google.com https://*.googleapis.com; frame-ancestors 'none';"

[[redirects]]
  from = "http://:splat"
  to = "https://:splat"
  status = 301

[template.environment]
  VITE_SUPABASE_URL = "Your Supabase URL"
  VITE_SUPABASE_ANON_KEY = "Your Supabase Anon Key"
  VITE_SITE_NAME = "Kopi Pendekar"
  VITE_ADMIN_EMAILS = "Your admin email"
  VITE_PAYMENT_INFO_TEXT = "Your payment instructions"
  VITE_QRIS_IMAGE_URL = "Your QRIS image URL"
