#!/bin/bash

echo "🚀 Setting up Supabase storage bucket for store icons..."

# This script sets up the 'store-icons' bucket in Supabase Storage
# Make sure you have the Supabase CLI installed and configured

echo "📋 Instructions:"
echo "1. Install Supabase CLI: npm install -g supabase"
echo "2. Login to Supabase: supabase login"
echo "3. Link your project: supabase link --project-ref YOUR_PROJECT_REF"
echo "4. Run this script or manually create the bucket"
echo ""

echo "🔧 Creating storage buckets 'store-icons' and 'menu-photos'..."

# Create the storage buckets using Supabase CLI
supabase storage buckets create store-icons --public || echo "⚠️  store-icons bucket might already exist"
supabase storage buckets create menu-photos --public || echo "⚠️  menu-photos bucket might already exist"

echo ""
echo "📝 Manual Setup (if CLI doesn't work):"
echo "1. Go to your Supabase Dashboard"
echo "2. Navigate to Storage"
echo "3. Create a new bucket named 'store-icons'"
echo "4. Create another bucket named 'menu-photos'"
echo "5. Make both buckets PUBLIC"
echo "6. Set up RLS policies for authenticated users"
echo ""

echo "🔐 Setting up Row Level Security (RLS) policies..."

echo "⚠️  IMPORTANT: You CANNOT run DDL commands on storage.objects table directly!"
echo "   RLS policies for storage must be set up through the Supabase Dashboard."
echo ""

echo "📋 STEP-BY-STEP: Setting up menu-photos bucket in Supabase Dashboard"
echo "=================================================================="
echo ""

echo "🎯 IMPORTANT: You need to be the project OWNER to set up storage policies"
echo ""

echo "📋 STEP 1: Create Storage Buckets"
echo "=================================="
echo ""
echo "1.1. Go to your Supabase Dashboard"
echo "1.2. Click 'Storage' in the left sidebar"
echo "1.3. Click 'New Bucket' button"
echo ""
echo "1.4. Create 'store-icons' bucket:"
echo "   • Name: store-icons"
echo "   • Public bucket: ✅ YES (check the box)"
echo "   • Click 'Create Bucket'"
echo ""
echo "1.5. Create 'menu-photos' bucket:"
echo "   • Name: menu-photos"
echo "   • Public bucket: ✅ YES (check the box)"
echo "   • Click 'Create Bucket'"
echo ""

echo "📋 STEP 2: Set Up RLS Policies for Each Bucket"
echo "==============================================="
echo ""
echo "2.1. For 'store-icons' bucket:"
echo "   • Click on 'store-icons' bucket"
echo "   • Go to 'Policies' tab"
echo "   • Click 'New Policy'"
echo ""
echo "   Policy 1 - Upload Permission:"
echo "   • Policy Name: 'Authenticated users can upload store icons'"
echo "   • Operation: INSERT"
echo "   • Target Roles: authenticated"
echo "   • Policy Definition: bucket_id = 'store-icons'"
echo "   • Click 'Save Policy'"
echo ""
echo "   Policy 2 - Public Read Permission:"
echo "   • Policy Name: 'Public read access for store icons'"
echo "   • Operation: SELECT"
echo "   • Target Roles: public"
echo "   • Policy Definition: bucket_id = 'store-icons'"
echo "   • Click 'Save Policy'"
echo ""

echo "2.2. For 'menu-photos' bucket:"
echo "   • Click on 'menu-photos' bucket"
echo "   • Go to 'Policies' tab"
echo "   • Click 'New Policy'"
echo ""
echo "   Policy 1 - Upload Permission:"
echo "   • Policy Name: 'Authenticated users can upload menu photos'"
echo "   • Operation: INSERT"
echo "   • Target Roles: authenticated"
echo "   • Policy Definition: bucket_id = 'menu-photos'"
echo "   • Click 'Save Policy'"
echo ""
echo "   Policy 2 - Public Read Permission:"
echo "   • Policy Name: 'Public read access for menu photos'"
echo "   • Operation: SELECT"
echo "   • Target Roles: public"
echo "   • Policy Definition: bucket_id = 'menu-photos'"
echo "   • Click 'Save Policy'"
echo ""

echo "📋 STEP 3: Verify Setup"
echo "======================="
echo ""
echo "3.1. Check buckets exist:"
echo "   • Go to Storage section"
echo "   • Verify both 'store-icons' and 'menu-photos' appear"
echo "   • Both should show as 'Public'"
echo ""

echo "3.2. Check policies:"
echo "   • Click each bucket"
echo "   • Go to 'Policies' tab"
echo "   • Verify you have 2 policies per bucket"
echo ""

echo "3.3. Test upload:"
echo "   • Try uploading a small image in admin dashboard"
echo "   • Should work without errors"
echo ""

echo "📋 STEP 4: Troubleshooting"
echo "=========================="
echo ""
echo "❌ 'Permission denied' errors?"
echo "   → Make sure you're logged in as project owner"
echo "   → Check that you're in the correct Supabase project"
echo ""

echo "❌ 'Bucket not found' errors?"
echo "   → Double-check bucket names are exact"
echo "   → Verify buckets are set to PUBLIC"
echo ""

echo "❌ Upload still fails?"
echo "   → Check browser console for detailed error messages"
echo "   → Verify RLS policies are correctly configured"
echo ""

echo "🎉 SUCCESS INDICATORS:"
echo "======================"
echo ""
echo "✅ Both buckets appear in Storage section"
echo "✅ Both buckets show as 'Public'"
echo "✅ Each bucket has 2 policies in Policies tab"
echo "✅ Admin can upload store icons and menu photos"
echo "✅ Images display correctly in the app"
echo ""

echo "🔧 ALTERNATIVE: Command Line Setup"
echo "=================================="
echo ""
echo "If you prefer using Supabase CLI:"
echo ""
echo "supabase storage buckets create store-icons --public"
echo "supabase storage buckets create menu-photos --public"
echo ""
echo "📝 Note: CLI setup still requires manual policy configuration in Dashboard"
echo ""

echo "✅ SETUP COMPLETE!"
echo "=================="
echo ""
echo "🎯 Your storage buckets are now ready for:"
echo "   • Store icon uploads (admin settings)"
echo "   • Menu photo uploads (admin menu management)"
echo "   • Public access for displaying images"
echo ""

echo "🚀 Ready to use all features!"
echo ""

echo "💡 TIP: Keep this window open while setting up - you can refer back to these steps!"
